package com.ceotracker.service;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.regex.Pattern;

public class ActivityNormalizer {

    private static final Map<Pattern, String> RULES = new LinkedHashMap<>();

    static {
        RULES.put(pattern(
            "AGROALIMENTAIRE|ALIMENTAIRE|ALIMENTATION|BOISSON|CONFISERIE|TABAC|SUCRE|"
            + "HUILE|FARINE|CONSERVE|BISCUIT|LEVURE|EPICER|VOLAILLE|POISSON|BOULANGER|"
            + "PATISSE|ABATTOIR|VIANDE|FRUITS|LEGUME|LAITIER|MINOTERIE|SEMOULE|PATE|"
            + "BRIOCHE|CHOCOLAT|JUS|SODA|BRASSERIE|ALIMENT.*ANIMALE|BOISSONS GAZEUSES|"
            + "EMBOUTEILLAGE|CONDITIONNEMENT|PRODUCTION TABAC|CARN,?E|AGRICOLE|AGRICULTURE|"
            + "PÊCHE|PECHE|FORESTIER|ÉLEVAGE|ELEVAGE|PISCICULTURE|HALIEUTIQUE|PALMIER|CULTURE"
        ), "Agroalimentaire & Agriculture");

        RULES.put(pattern(
            "CIMENTERIE|CIMENT|BTP|CONSTRUCTION|CARRIERE|CARRIÈRE|MATERIAU|MATÉRIAU|"
            + "MARBRE|PIERRE|BATIMENT|BÂTIMENT|TRAVAUX|GALVANISATION|ASCENSEUR|"
            + "CHAUDRONNERIE|ARMATURE|FERROVIAIRE|CONDUITE.*EAU|FONTAINE|ABAT.?JOUR|"
            + "MENUISERIE|PLOMBERIE|REVETEMENT|REVÊTEMENT|"
            + "MINE|MINIÈRE|MINIERE|MÉTALLURGIE|MÉTALLURGIQUE|ALUMINIUM|ACIER|FONDERIE|"
            + "MINERAIS|MINÉRAUX|ABRASIF|TOLERIE|TÔLERIE|"
            + "ENERGIE|ÉNERGIE|HYDROCARBURE|CARBURANT|RAFFINAGE|PÉTROLIER|PÉTROLE|"
            + "GAZ|CENTRALE THERMIQUE|"
            + "AUTOMOBILE|AUTO|CÂBLAGE|CABLAGE|PNEUMATIQUE|RACCORD|GARAGE|"
            + "CONCESSION|PIÈCE.*AUTO|PIECE.*AUTO|VEHICULE|VÉHICULE|CARROSSERIE"
        ), "Industrie Lourde");

        RULES.put(pattern(
            "PHARMACEUTIQUE|PHARMA|MÉDICAMENT|LABORATOIRE|ANALYSE.*MÉDICAL|"
            + "SANTÉ|PARAPHARMACIE|MATÉRIEL.*MÉDICAL|"
            + "CHIMIE|CHIMIQUE|PEINTURE|COLLE|PRODUIT.?ENTRETIEN|SOLVANT|"
            + "DÉTERGENT|DETERGENT|ENCRE|PLASTIQUE|POLYMÈRE|POLYMERE|"
            + "RÉSINE|RESINE|CAOUTCHOUC|PARFUM|COSMÉTIQUE|COSMETIQUE|"
            + "CARTON|PAPIER|EMBALLAGE|IMPRESSION|IMPRIMERIE|ÉTIQUETTE|ETIQUETTE|"
            + "GRAPHISME|PUBLICITÉ|PUBLICITE|PÂTE.?PAPIER|PATE.?PAPIER|"
            + "TEXTILE|HABILLEMENT|VÊTEMENT|VETEMENT|CONFECTION|MODE|PRÊT.?À.?PORTER|"
            + "TISSAGE|FILATURE|CUIR|MAROQUINERIE|CHAUSSURE"
        ), "Industrie Légère");

        RULES.put(pattern(
            "ÉLECTRICITÉ|ELECTRICITE|ÉLECTRIQUE|ELECTRIQUE|ÉLECTRONIQUE|ELECTRONIQUE|"
            + "ÉLECTROMÉNAGER|ELECTROMENAGER|RÉFRIGÉRATEUR|MATÉRIEL.?ÉLECTRIQUE|MATERIEL.?ELECTRIQUE|"
            + "TÉLÉCOMMUNICATION|TELECOMMUNICATION|TÉLÉCOM|TELECOM|INFORMATIQUE|"
            + "RÉSEAU|RESEAU|INTERNET|DIGITAL|MOBILE|FIBRE|DATA|TÉLÉPHONIE"
        ), "Numérique & Électricité");

        RULES.put(pattern(
            "TRANSPORT|LOGISTIQUE|MESSAGERIE|LIVRAISON|PORT|CABOTAGE|MARITIME|"
            + "NAVALE|FRET|COURSIER|VOYAGE|AÉRIEN|AERIEN"
        ), "Transport & Logistique");

        RULES.put(pattern(
            "FINANCE|BANQUE|ASSURANCE|CRÉDIT|CREDIT|HOLDING FINANCIER|"
            + "BANCAIRE|INVESTISSEMENT|FONDS|TRÉSORERIE|TRESORERIE|"
            + "GRANDE DISTRIBUTION|DISTRIBUTION|COMMERCE|COMMERCIALISATION|"
            + "IMPORTATION|IMPORT|EXPORT|CENTRE COMMERCIAL|MARCHÉ|MARCHE|"
            + "SUPERMARCHÉ|SUPERMARCHE|SUPERETTE|SUPÉRETTE|DISTRIBUTIONNELLE|"
            + "DOMICILIATION|QUINCAILLERIE|"
            + "SÉCURITÉ|SECURITE|GARDIENNAGE|SURVEILLANCE|ALARME|INCENDIE|"
            + "PROTECTION|NETTOYAGE|PROPRETÉ|PROPRETE|SALUBRITÉ|SALUBRITE|"
            + "CONSEIL|CONSULTING|ENGINEERING|BUREAU.?ÉTUDE|BUREAU.?ETUDE|"
            + "FORMATION|ENSEIGNEMENT|ÉCOLE|ECOLE|RECRUTEMENT|TRAVAIL TEMPORAIRE|"
            + "HÔTELLERIE|HOTELLERIE|HÔTEL|HOTEL|TOURISME|RESTAURATION|"
            + "HÉBERGEMENT|HEBERGEMENT|LOISIR"
        ), "Commerce, Finance & Services");
    }

    private static Pattern pattern(String keywords) {
        return Pattern.compile("\\b(" + keywords + ")\\b", Pattern.CASE_INSENSITIVE | Pattern.UNICODE_CASE);
    }

    public static String normalize(String raw) {
        if (raw == null || raw.isBlank()) return null;
        String upper = raw.toUpperCase().replaceAll("[\\s,:;./\\\\()\\[\\]{}]+", " ").trim();
        return RULES.entrySet().stream()
            .filter(e -> e.getKey().matcher(upper).find())
            .map(Map.Entry::getValue)
            .findFirst()
            .orElse("Autre");
    }
}
